[workspace]
members = ["xtask", "capable", "capable-common"]

[package]
name = "RootAsRole"
version = "3.0.0-alpha.4"
authors = ["Eddie Billoir <eddie.billoir@irit.fr>"]
edition = "2021"
default-run = "sr"

#[features]
#cursive_lib = [ "cursive" ]
#srlibs = [ "pam-client", "bitflags" ]

[[bin]]
name = "sr"
path = "src/sr/main.rs"


[[bin]]
name = "chsr"
path = "src/chsr/main.rs"

[build-dependencies]
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
pcre2 = "0.2.4"
regex = "1.9.1"
serde = { version = "1.0.185" }
serde_json = "1.0.113"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
libc = "0.2.153"
strum = { version = "0.26.2", features = ["derive"] }
semver = { version = "1.0.22", features = ["serde"] }
nix = { version = "0.28.0", features = ["user","process", "signal", "fs"] } 
#sudoers-reader = { path = "sudoers-reader" }
clap = { version = "4.5.3", features = ["derive"] }
capctl = "0.2.4"
pcre2 = "0.2.6"
serde = { version = "1.0.197", features=["rc"] }
serde_json = "1.0.114"
ciborium = "0.2.2"
glob = "0.3.1"
pam-client = { version = "0.5.0", git = "https://gitlab.com/LeChatP/rust-pam-client.git" }
bitflags = { version = "2.5.0" }
shell-words = "1.1.0"
syslog-tracing = "0.3.0"
linked_hash_set = { version = "0.1.4" }
derivative = "2.2.0"
sha2 = "0.10.8"
sha1 = "0.10.6"
md5 = "0.7.0"
chrono = "0.4.37"
pty-process = "0.4.0"
once_cell = "1.19.0"

[dev-dependencies]
env_logger = "*"
test-log = { version = "0.2.12", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "fmt"] }
