[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[lints.clippy]
pedantic = { level = "warn", priority = 1 }
nursery = { level = "warn", priority = 1 }
unwrap_used = { level = "deny", priority = 2 }
similar_names = { level = "allow", priority = 2 }
should_implement_trait = { level = "allow", priority = 2 }

[dependencies]
anyhow = { version = "1.0.104", default-features = false }
clap = { version = "4.5.16", default-features = false, features = ["derive", "std"] }
serde = { version = "1.0", default-features = false, features=["std", "rc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
jiff = { version = "0.2", default-features = false, features = ["std"] }
capctl = { version = "0.2.4", default-features = false, features = ["serde", "std"] }
nix = { version = "0.31", default-features = false, features = ["user","process", "signal", "fs"] } 
glob = { version = "0.3.1", default-features = false }
log = { version = "0.4.22", default-features = false, features = ["std"] }
env_logger = { version = "0.11", default-features = false }
konst = { version= "0.4", default-features = false, features = ["parsing_proc", "iter"] }
semver = { version = "1.0", default-features = false, features = ["std", "serde"] }

[features]
default = ["cli", "ebpf", "deploy"]
cli = []
ebpf = []
deploy = []

[lints.rust]
dead-code = { level = "allow" }
