Vagrant.require_version ">= 2.1.0" # 2.1.0 minimum required for triggers

user = ENV['RH_USER']
password = ENV['RH_PW']
pool_id = ENV['RH_POOL']
if !user or !password
  puts 'Required environment variables not found. Please set RH_USER and RH_PW'
  abort
end


register_script = %{
if ! subscription-manager status; then
  sudo subscription-manager register --username="#{user}" --password="#{password}"
  sudo subscription-manager attach --pool="#{pool_id}"
fi
}

unregister_script = %{
if subscription-manager status; then
  sudo subscription-manager unregister
fi
}

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel9"
  # Disable guest additions check, because at this point the VM 
  # will not be registered with RHEL via subsctiption-manager 
  # and yum install <anything> will not work.


  config.vm.provision "shell", inline: register_script

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y git gcc make
    sudo -u vagrant sh -c 'git clone -b develop https://github.com/LeChatP/RootAsRole;
      cd RootAsRole;
      ./dependencies.sh -y;
      sudo ./configure.sh -y;
      PROFILE=debug make install;
      dosr capable -j cat /etc/shadow;'
    SHELL

  config.trigger.before :destroy do |trigger|
    trigger.name = "Before Destroy trigger"
    trigger.info = "Unregistering this VM from RedHat Subscription Manager..."
    trigger.warn = "If this fails, unregister VMs manually at https://access.redhat.com/management/subscriptions"
    trigger.run_remote = {inline: unregister_script}
    trigger.on_error = :continue
  end # trigger.before :destroy
end # vagrant configure