Vagrant.configure("2") do |config|
    config.vm.box = "generic/fedora37"
  
    config.vm.provision "shell", inline: <<-SHELL
      dnf install -y git gcc make
      sudo -u vagrant sh -c 'git clone -b develop https://github.com/LeChatP/RootAsRole;
      cd RootAsRole;
      ./dependencies.sh -y;
      sudo ./configure.sh -y;
      PROFILE=debug make install;
      RUST_LOG=debug capable -j cat /etc/shadow;'
    SHELL
  end
  