[book]
authors = ["LeChatP"]
language = "en"
src = "src"
title = "RootAsRole Documentation"
description = "Practical documentation for RootAsRole"

[output.html]
site-url = "/RootAsRole/"
git-repository-url = "https://github.com/LeChatP/RootAsRole/tree/master/book"
edit-url-template = "https://github.com/LeChatP/RootAsRole/edit/master/book/{path}"
theme = "theme"
default-theme = "rust"
additional-css = ["theme/css/book.css"]

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

[preprocessor.bib]
title="References"
hb-tpl = "references.hbs"
cite-hb-tpl = "cite.hbs"
bibliography = "references.bib"