[book]
authors = ["LeChatP"]
language = "en"
src = "src"
title = "RootAsRole Documentation"
description = "Practical documentation for RootAsRole"

[output.html]
git-repository-url = "https://github.com/LeChatP/RootAsRole/tree/main/book"
edit-url-template = "https://github.com/LeChatP/RootAsRole/edit/main/book/{path}"

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

[preprocessor.bib]
title="References"
hb-tpl = "references.hbs"
cite-hb-tpl = "cite.hbs"
bibliography = "references.bib"