name: Build Project

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update version
      run: sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo ./dependencies.sh -yd
        sudo ./configure.sh -yd
        echo "/home/runner/.cargo/bin" >> $GITHUB_PATH
    - name: Configure PAM
      run: |
        sudo bash -c 'echo "#%PAM-1.0
        auth    [success=1 default=ignore]  pam_permit.so
        auth    requisite                   pam_permit.so
        auth    required                    pam_permit.so
        account [success=1 default=ignore]  pam_permit.so
        account requisite                   pam_permit.so
        account required                    pam_permit.so
        session [success=1 default=ignore]  pam_permit.so
        session requisite                   pam_permit.so
        session required                    pam_permit.so" | tee /etc/pam.d/sr'
    - name: Add read access on config on rootasrole... Because Github Actions...
      run: sudo chmod a+r /etc/security/rootasrole.json
    - name: print config
      run: cat /etc/security/rootasrole.json
    - name: getenv
      run: env
    - name: Install Project
      run: sudo -E make -e install
    - name: Run Sr
      run: /usr/bin/sr -h
    - name: Run Chsr with sr
      run: sr /usr/bin/chsr -h
