name: Build Project

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Configure PAM
      run: |
        sudo bash -c 'echo "#%PAM-1.0
        auth    [success=1 default=ignore]  pam_permit.so
        auth    requisite                   pam_permit.so
        auth    required                    pam_permit.so
        account [success=1 default=ignore]  pam_permit.so
        account requisite                   pam_permit.so
        account required                    pam_permit.so
        session [success=1 default=ignore]  pam_permit.so
        session requisite                   pam_permit.so
        session required                    pam_permit.so" | tee /etc/pam.d/dosr'
    - name: Install RootAsRole
      run: cargo xtask install -bip sudo
    - name: print config
      run: dosr cat /etc/security/rootasrole.json
    - name: getenv
      run: env
    - name: Run dosr
      env:
        RUST_LOG: debug
      run: /usr/bin/dosr -h
    - name: Run Chsr with dosr
      run: dosr /usr/bin/chsr -h
