name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update version
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo ./configure.sh
    - name: Build Project
      run: sudo make -e install
    - name: Run Project
      run: sr -h
  rust-build:
    runs-on: ubuntu-latest
    env:
      working-directory: "role-manager"
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Setup project
      run: sudo ./configure.sh
    - name: Build Project
      run: sr cargo build --release
      working-directory: ${{ env.working-directory }}
    - name: Run Project
      run: sr cargo run --release -- -h
      working-directory: ${{ env.working-directory }}