name: Build Project

on:
  push:
    branches:
      - 'main'
      - 'reorganisation'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Configure PAM
      run: |
        sudo bash -c 'echo "#%PAM-1.0
        auth    [success=1 default=ignore]  pam_permit.so
        auth    requisite                   pam_permit.so
        auth    required                    pam_permit.so
        account [success=1 default=ignore]  pam_permit.so
        account requisite                   pam_permit.so
        account required                    pam_permit.so
        session [success=1 default=ignore]  pam_permit.so
        session requisite                   pam_permit.so
        session required                    pam_permit.so" | tee /etc/pam.d/sr'
    - name: Install RootAsRole
      run: sudo -E cargo xtask install -bia
    - name: Add read access on config on rootasrole... Because Github Actions...
      run: sudo chmod a+r /etc/security/rootasrole.json
    - name: print config
      run: cat /etc/security/rootasrole.json
    - name: getenv
      run: env
    - name: Run Sr
      env:
        RUST_LOG: debug
      run: /usr/bin/sr -h
    - name: Run Chsr with sr
      run: sr /usr/bin/chsr -h
