name: Criterion Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST: 1
      DEBUG: 1
      COV: 1

    steps:
    - uses: actions/checkout@v2

    - name: Update version
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo -E ./configure.sh
    - name: Build Unit Tests
      run: make -e build_unit_test
    - name: Run Unit Tests
      run: ./bin/unit_test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        gcov: true