name: Deploy pkg to GitHub Packages

## never trigger this workflow automatically
on:
  push: 
    tags:
      - 'v*.*.*'
    branches:
      - 'reorganisation'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Install Dependencies
        run: cargo xtask dependencies -dip sudo

      - name: Build deb and rpm packages
        run: cargo xtask deploy debian redhat

      - name: Publish to GitHub Packages
        run: cargo publish --manifest-path xtask/Cargo.toml --token ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        