name: Rust Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build code
      run: cargo build --all --release
      working-directory: role-manager

    - name: Format code with Rustfmt
      run: cargo fmt --all -- --check
      working-directory: role-manager

    - name: Run Clippy
      run: cargo clippy --all -- -D warnings
      working-directory: role-manager

    - name: Build and run tests
      run: cargo test --all --
      working-directory: role-manager
