name: Project Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  rust-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: llvm-tools-preview
        override: true

    - name: Install grcov
      run: cargo install grcov
    
    - name: Install Dependencies
      run: sudo ./dependencies.sh -yd
    
    - name: Install file configuration
      run: sudo ./configure.sh -yd
    
    - name: run tests with coverage
      run: cargo test
      env: 
        RUST_LOG: debug
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: '-Cinstrument-coverage'
        LLVM_PROFILE_FILE: 'cargo-test-%p-%m.profraw'
      continue-on-error: true
    
    - name: generate report
      run: grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/debug/rootasrole.lcov
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: target/debug/rootasrole.lcov
        flags: unittests
