name: Project Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  rust-coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Update apt-get
      run: apt update -y
    
    - name: Install sudo
      run: apt install sudo -y
    
    - name: Install Dependencies
      run: ./dependencies.sh -yd
    
    - name: Install file configuration
      run: sudo bash ./configure.sh -yd
    
    - name: run tests with coverage
      run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --bin chsr --bin sr --exclude-files capable* capable-ebpf/src/vmlinux.rs capable/src/main.rs build.rs --out Xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: cobertura.xml
        flags: unittests

    - name: run tests with coverage as Admin
      run: sudo -E /usr/local/cargo/bin/cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --bin chsr --bin sr --exclude-files capable* capable-ebpf/src/vmlinux.rs capable/src/main.rs build.rs --out Xml

    - name: Upload coverage reports to Codecov as Admin
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: cobertura.xml
        flags: admin-unittests