name: Project Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  rust-coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Update apt-get
      run: apt update -y
    
    - name: Install sudo
      run: apt install sudo -y

    - name: Install Dependencies
      run: cargo xtask dependencies -dip sudo
    
    - name: build integration coverage
      run: sudo -E /usr/local/cargo/bin/cargo +nightly coverage
      env:
        RAR_AUTHENTICATION: skip
        RAR_CFG_PATH: target/rootasrole.json
        SKIP_BUILD: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: cobertura.xml
        flags: unittests